### ISSUE TITLE
Unable to install Slick on AEM 6

### ISSUE THREAD

**Issue by boser87** [auniverseaway/slick#1]
I'm struggling to install Slick on AEM 6. I tried to add the additional dependencies (Sightly, JCR compiler, ...) embedding them within the bundle using maven-bundle-plugin but I still have the Slick bundle not active because many other dependencies appear to be unresolved. Could you please provide more details on the installation steps?
Thank you!

**Comment by auniverseaway** [comment]
Slick was never intended to be installed on AEM, only pure Sling. I would almost discourage it as it would require changing some key pieces significantly. For example, the Sightly implementation on AEM and Sling are different. One is org.apache.sling.scripting.sightly (Sling) and one is com.adobe.cq.sightly (AEM). The list goes on.

**Comment by boser87** [comment]
Got it. Thank you for the explanation.
